### ISSUE TITLE
请问graylog的conf应该如何设置？能否举个例子？

### ISSUE THREAD

**Issue by tungh** [gogap/logrus_mate#12]
mike {

        level = "error"

        formatter.name = "text"
        formatter.options  {
                            force-colors      = false
                            disable-colors    = false
                            disable-timestamp = false
                            full-timestamp    = false
                            timestamp-format  = "2006-01-02 15:04:05"
                            disable-sorting   = false
        }

        hooks {
                expander {}

                graylog {
                    address = ""
                    extra = ""
                }
        }
}

应该如何填写？

**Comment by xujinzheng** [comment]
你想使用哪个插件？或者你期望的效果是什么，我帮你看看

**Comment by tungh** [comment]
我想使用logrus_mate里hook的graylog，把log记录到graylog里面。
期望的效果就是，每次的log都发送到graylog里面。

**Comment by xujinzheng** [comment]
我们可以看一下 hooks/graylog/graylog_hook.go

配置文件的结构体如下

```go
type GraylogHookConfig struct {
	Address string
	Extra   map[string]interface{}
}
```

实际上获取配置的方法也是这样的

```go
conf.Address = config.GetString("address")

extraConf := config.GetConfig("extra")
keys := extraConf.Keys()
extra := make(map[string]interface{}, len(keys))
```

所以，必填项是 `address`

```hocon
mike {
        level = "error"
        hooks {
                graylog {
                   address = "ip:port"
                    extra {}
                }
        }
}
```
![image](https://user-images.githubusercontent.com/885569/28950278-2ef6b794-78f5-11e7-91c1-4357344ac8f7.png)


address 是你在 graylog 里创建的 inputs, 选择 [GELF UDP], 然后点 Launch new input, 
创建完成后，用logrus_mate 发日志，则可以看到右侧的NetworkIO

如果你使用了 gogap/errors 包，那么我们平时用logrus打Error时，可以把error里面的详细信息都打印出来，前提是在 hooks 里加 expander {}插件

```hocon
mike {
        level = "error"
        hooks {
                expander {}
                graylog {
                   address = "ip:port"
                    extra {}
                }
        }
}
```

打印效果如下：

![image](https://user-images.githubusercontent.com/885569/28950331-b6e21e78-78f5-11e7-9932-0219bd254f56.png)

**Comment by tungh** [comment]
非常感谢，请问extra 是做什么用的？

**Comment by xujinzheng** [comment]
你可以看这个插件的代码
https://github.com/gemnasium/logrus-graylog-hook/blob/master/graylog_hook.go#L169
