### ISSUE TITLE
About sirupsen and Sirupsen, different from release and master

### ISSUE THREAD

**Issue by spiderpoison** [gogap/logrus_mate#19]
when i want to use logrus_mate, it give me error "case-insensitive import collision: "vcs.taiyouxi.net/vendor/github.com/sirupsen/logrus" and "vcs.taiyouxi.net/vendor/github.com/Sirupsen/logrus"

so should is use master instead of release?

**Comment by xujinzheng** [comment]
I think you'd better to use master branch, because the author of logrus was changed the github org name from `Sirupsen` to `sirupsen`, for compatibility reason, I tag the old branch.
