### ISSUE TITLE
写文件log，按天记录

### ISSUE THREAD

**Issue by dimkua** [gogap/logrus_mate#2]
自己写了个第三方文件Writers，写log前能否调用Writers里面的方法(比如before_write)判断下生成新的io.Writer

**Comment by xujinzheng** [comment]
hooks/file 这个也是写文件log，按天记录的，你可以看看是否满足你需求

建议你是写hook，而不是写一个 writer, 因为 hook 能支持较为复杂的逻辑

**Comment by dimkua** [comment]
loggers的配置如下：
`{
            "name": "logger",
            "config": {
                "development": {
                    "out": {
                        "name": "stdout",
                        "options": {}
                    },
                    "level": "debug",
                    "formatter": {
                        "name": "json"
                    },
                    "hooks": [
                        {
                            "name": "file",
                            "options": {
                                "filename": "1.log",
                                "maxlines": 1000,
                                "maxsize": 1024,
                                "daily": true,
                                "maxdays": 7,
                                "rotate": true,
                                "level": 3
                            }
                        }
                    ]
                }
            }
        }`

hooks/file配置怎么额外有个level，没使用全局的level？
另外1.log记录的日志没使用定义的json格式
`[-] 2016/05/31 13:35:44 [ERROR] 111
/home/wjb/Document/go/src/repo.gokuai.cn/gokuai/webhook/logger/logger.go:57
[-] 2016/05/31 13:35:44 [INFO] 222
/home/wjb/Document/go/src/repo.gokuai.cn/gokuai/webhook/logger/logger.go:41`

**Comment by xujinzheng** [comment]
这个是指 `file` 这个插件在什么级别以上才输出，因为 logrus 本身是支持多插件执行的，那么插件本身可以做level的判断

**Comment by dimkua** [comment]
恩，看到其它几个hook没有level，file有感觉奇怪
file的输出格式不是json，这个是什么原因？

**Comment by xujinzheng** [comment]
这个插件是别人移植的，本身只支持行格式的，比较简易，但是够用

**Comment by dimkua** [comment]
好吧，我再实现个hook好了
