### ISSUE TITLE
What purpose of using hijack mode? 

### ISSUE THREAD

**Issue by vagruchi** [gogap/logrus_mate#6]
Saw some changes in repository. Can't understand purpose of using fixed notation for configuring and hijack mode.

**Comment by xujinzheng** [comment]
It will more scalability, you could create new logger by `logrus.New()`, then use config to hijack it, then the new logger's config will be set, and the logger also could be hijack more than once, if your env changed, you just hijack again, then the config will take effect.

the hijack mode also could hijack logrus.StandardLogger(), then we could use logurs.XXXX for print errors, if we want change the logger's config, just hijack logrus.StandardLogger() again.

**Comment by vagruchi** [comment]
Ok. But can we use another string format for configure logger? (For example: TOML) 
In previous versions for configuring we use struct. This struct could be filled by reflection. 
Now I can't see ways to do it.

**Comment by xujinzheng** [comment]
my latest commit are support customize config provider.
