### ISSUE TITLE
如何按天生成日志文件？

### ISSUE THREAD

**Issue by dgqypl** [gogap/logrus_mate#7]
我按照example/main.go中的代码和mate.conf.example，但运行时报这个错：
logurs mate: hook not registerd

我的代码：
`	mate, err := logrus_mate.NewLogrusMate(logrus_mate.ConfigFile("mate.conf"))

	newLoger := logrus.New()

	if err = mate.Hijack(newLoger, "mike"); err != nil {
		fmt.Println(err)
		return
	}

	// newLogger is Hijackt by mike config
	newLoger.Debug("You could not see me")
	newLoger.Errorln("Hello Error Level")

mike {

        level = "error"

        formatter.name = "text"
        formatter.options  {
                            force-colors      = false
                            disable-colors    = true
                            disable-timestamp = false
                            full-timestamp    = false
                            timestamp-format  = "2006-01-02 15:04:05"
                            disable-sorting   = false
        }

        hooks {

                file {
                    filename = "1.log"
                    daily = true
                    rotate = true
                }
        }
}

`

请帮忙看一下是怎么回事？

**Comment by xujinzheng** [comment]
```go
import (
    _ "github.com/gogap/logrus_mate/hooks/file"
)
```
