### ISSUE TITLE
name conflict with Logrus

### ISSUE THREAD

**Issue by tanmayambre** [gogap/logrus_mate#9]
The github.com/sirupsen/logrus/ is now lower case. All the imports in this repo has Cpitalized github.com/Sirupsen/logrus/ version. 
Can you change it to lowercase as indicated by README of github.com/Sirupsen/logrus.

**Comment by xujinzheng** [comment]
please see issue:
https://github.com/sirupsen/logrus/issues/451

**Comment by tanmayambre** [comment]
Thanks.
